### ISSUE TITLE
colour coding of types

### ISSUE THREAD

**Issue by pmackay** [nichtich/wikidata-taxonomy#17]
Very handy tool :)

I just tried this and found that the colour coding for types is pretty dark being dark blue:

![screen shot 2017-02-27 at 11 41 36](https://cloud.githubusercontent.com/assets/115115/23360189/fc8c6824-fce1-11e6-8b4e-c948517e94cf.png)

It might be my settings, etc, but why not make this colour somewhat brighter? Perhaps white? The green of the Q-numbers is much more readable.

**Comment by nichtich** [comment]
Well, color is also a matter of taste and depends on Operating System settings but you are right, so I changed it into white (see release 0.2.10).

**Comment by pmackay** [comment]
Great, thanks!
