### ISSUE TITLE
An OR list in the --mappings option

### ISSUE THREAD

**Issue by ppKrauss** [nichtich/wikidata-taxonomy#23]
The "OR list" have many applications, see [one example here](https://github.com/schemaorg/schemaorg/issues/280#issuecomment-340254939) or [this analytic query](https://github.com/okfn-brasil/schemaOrg-Wikidata-Map/blob/master/docs/quering-Wikidata.md)...

**Suggestion**: use comma-separated list as `P1709,P2888` to recognize an "OR list".

Example:  

* `wdtaxonomy -m P1709 Q33999 |grep schema.org` is the default command, but returns empty.

* `wdtaxonomy -m P1709,P2888 Q33999 |grep schema.org` as  default command is better, will return something.

**Comment by nichtich** [comment]
Done in the master branch. How about some predefined list of common mapping properties or getting the list as sub-properties of [Q30249126](https://www.wikidata.org/wiki/Q30249126)? Maybe this way:

    wdtaxonomy -m all Q33999

**Comment by nichtich** [comment]
Implemented in 0.5.0, including shortcut keywords. The output, however does not distinguish mapping types yet (#26).
