### ISSUE TITLE
CSV output should be quoted

### ISSUE THREAD

**Issue by pmackay** [nichtich/wikidata-taxonomy#38]
I was pulling a CSV output of the `product` taxonomy tree, which is quite large. It failed to parse as CSV because labels that include a quote character are not quoted themselves, so the first item to fail was:

`-----,Q6109076,JTL-E .500 S&W Magnum 12",1,0,`

Would it make sense for all `label`s to be quoted by default?

**Comment by nichtich** [comment]
I left it unquoted because so it is easier to process (just split at `,`) but you are right. I'll change this and add TSV as alternative.

**Comment by nichtich** [comment]
Fixed in version 0.6.4
