### ISSUE TITLE
getting "SPARQL request failed" for every call

### ISSUE THREAD

**Issue by finin** [nichtich/wikidata-taxonomy#49]
I've been using wdtaxonomy (v 0.6.6) happily for many months on my macbook running 10.14.5.  Starting yesterday, every call I make (e.g., "wdtaxonomy -c Q5") produces an immediate "SPARQL request failed" message.

I tried capturing the sparql queries with --sparql and pasting that into the wikidata query service web page, and it they work.  I also tried passing the standard query service URL with  --sparql-endpoint and that did not help.  I tried uninstalling and then installing again, which did not fix the problem.  

Might it be due to this: https://lists.wikimedia.org/pipermail/wikidata/2019-June/013161.html ?

Any suggestions?

**Comment by nichtich** [comment]
Hi @finin, thanks for the feedback. Please try version 0.6.7!

**Comment by finin** [comment]
Great, Thanks for updating it!

--
Tim Finin,  Willard and Lillian Hackerman Chair in Engineering,  Computer
Science and
Electrical Engineering, U. Maryland, Baltimore County, 1000 Hilltop Circle,
Baltimore MD
21250. http://umbc.edu/~finin, finin@umbc.edu, tfinin@gmail.com,
mobile:410-499-3522

**Comment by mrcchef** [comment]
Hey, I have the latest version 0.6.7, still, it's happening with me.
This is the query that I ran :  wdtaxonomy -f csv Q735
Output: SPARQL request failed

**Comment by mrcchef** [comment]
Hey, I am facing the same issue!
I have the latest version i.e. 0.6.7
Query: wdtaxonomy -f csv  Q735
Output: SPARQL request failed

**Comment by finin** [comment]
Capturing the query with a -s flag and executing it directly on Wikidata
Query Service <https://query.wikidata.org/> show that the problem is due to
a query timeout.

The wdtaxonomy query with a -b flag does work

wdtaxonomy -b -f csv Q735


so apparently, counting all of the instances takes too much time.

--
Tim Finin, Computer Science & Electrical Engineering, Univ. Maryland
Baltimore County
1000 Hilltop Circle, Baltimore, MD 21250.  http://umbc.edu/~finin,
***@***.***

**Comment by finin** [comment]
Capturing the query with a -s flag and executing it directly on Wikidata Query Service show that the problem is due to a query timeout. Adding a -b flag to the query does work, so apparently, counting all of the instances takes too much time.

wdtaxonomy -b -f csv Q735

**Comment by jaygray0919** [comment]
Had a similar issue.
Here is the dialog: https://github.com/nichtich/wikidata-taxonomy/issues/52
now works as advertised
/jay
