### ISSUE TITLE
sparqlRequest bug involving wdk.simplifySparqlResults?

### ISSUE THREAD

**Issue by maxlath** [nichtich/wikidata-taxonomy#5]
great module!
If you have an example where `wdk.simplifySparqlResults` crashes as suggested by [your comment](https://github.com/nichtich/wikidata-taxonomy/blob/master/wdtaxonomy.js#L69), I would be happy to have a look at it :)

**Comment by nichtich** [comment]
Try this with `wdsparql --simplify`. The query is not optimized but valid:

```
SELECT ?item ?itemLabel ?broader ?parents
WHERE
{
    {
        SELECT ?item (count(distinct ?parent) as ?parents) {
            ?item wdt:P279* wd:Q1
            OPTIONAL { ?item wdt:P279 ?parent }
        } GROUP BY ?item
    }
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
    }
}
```

**Comment by maxlath** [comment]
ok, I [created an issue in the wikidata-sdk repo](https://github.com/maxlath/wikidata-sdk/issues/9), closing here
