### ISSUE TITLE
refactor as node module to be used in other projects

### ISSUE THREAD

**Issue by nichtich** [nichtich/wikidata-taxonomy#6]
The command line script should be a wrapper to a module

**Comment by nichtich** [comment]
Partly implemented in 0.2.6 but needs a stable JSON format before documentation or thoughts about how to use promises. There should be a simple function to be exported:

``` json
var wdtaxonomy = require('wikidata-taxonomy').taxonomy
var serialize = require('wikidata-taxonomy').serialize

var taxonomy = wdtaxonomy('Q123', options)
process.stdout.write(serialize(taxonomy, format))
```

This should better be documented.

**Comment by kevincfz** [comment]
Can you give some examples to use queryTaxonomy as a module?
In README you said
```js
const { queryTaxonomy } = require('wikidata-taxonomy');
```
Is the following correct to use it?
```js
queryTaxonomy('Q123', options)
```
If so, a few questions
1. what format is options? 
2. does the above line return a promise?

**Comment by nichtich** [comment]
Thanks for asking. I [extended  the documentation](https://github.com/nichtich/wikidata-taxonomy#usage-as-module).
